# Merge Mun_atlas e Zoonoses

In [2]:
import pandas as pd

# Criar DataFrames de exemplo
df1 = pd.read_csv(r'C:\Users\claud\OneDrive\Área de Trabalho\Iniciação Científica\Chikunguya-CAPTO\assets\data\MUN_Atlas.csv', encoding='latin1', sep=';')
df2 = pd.read_excel(r'C:\Users\claud\OneDrive\Área de Trabalho\Iniciação Científica\Chikunguya-CAPTO\assets\data\zoonoses2.xlsx')

# Mesclar os DataFrames com base no 'ID'
merged_df = pd.merge(df1, df2, on='ID', how='inner')  # Use 'outer' para manter todos os IDs

# Mostrar DataFrame mesclado
print(merged_df)

C:\Users\claud\AppData\Local\Temp\ipykernel_13448\1147024256.py:4: DtypeWarning: Columns (40,45,46,53,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,144,145,146,150,154,155) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv(r'C:\Users\claud\OneDrive\Área de Trabalho\Iniciação Científica\Chikunguya-CAPTO\assets\data\MUN_Atlas.csv', encoding='latin1', sep=';')

        ANO  UF  Codmun6       ID              Munic­pio ESPVIDA FECTOT  \
0      1991  11   110001  1100015  ALTA FLORESTA D'OESTE   62,01   4,08
1      2000  11   110001  1100015  ALTA FLORESTA D'OESTE    66,9   3,11
2      2010  11   110001  1100015  ALTA FLORESTA D'OESTE   70,75   2,24
3      1991  11   110002  1100023              ARIQUEMES   66,02   3,72
4      2000  11   110002  1100023              ARIQUEMES   69,52   2,77
...     ...  ..      ...      ...                    ...     ...    ...
16687  2000  52   522230  5222302          VILA PROPCIO   68,99   3,41
16688  2010  52   522230  5222302          VILA PROPCIO   73,09   2,67
16689  1991  53   530010  5300108               BRASLIA   68,87   2,33
16690  2000  53   530010  5300108               BRASLIA   73,86   1,96
16691  2010  53   530010  5300108               BRASLIA   77,35   1,75

       MORT1  MORT5 RAZDEP  ... Leptospirose Verminoses Cólera Difteria Tifo  \
0      45,58  58,05   73,5  ...            -          1      -        -    -
1      28,36  33,96  61,65  ...            -          1      -        -    -
2       23,8  25,49  47,37  ...            -          1      -        -    -
3      32,39  41,41  69,97  ...            -          -      -        -    -
4      21,68  25,99  59,88  ...            -          -      -        -    -
...      ...    ...    ...  ...          ...        ...    ...      ...  ...
16687   29,3   34,5  62,64  ...            -          1      -        -    -
16688   15,9   18,8  50,75  ...            -          1      -        -    -
16689  27,35  31,75  57,01  ...            -          -      -        -    -
16690  20,71  24,04  46,49  ...            -          -      -        -    -
16691  14,01  15,85  40,14  ...            -          -      -        -    -

      Malária Hepatite Febre amarela Dermatite Doença do aparelho respiratório
0           -        -             -         -                               -
1           -        -             -         -                               -
2           -        -             -         -                               -
3           -        -             -         -                               -
4           -        -             -         -                               -
...       ...      ...           ...       ...                             ...
16687       -        -             -         -                               -
16688       -        -             -         -                               -
16689       -        -             -         -                               -
16690       -        -             -         -                               -
16691       -        -             -         -                               -

[16692 rows x 253 columns]

In [3]:
# Salvar o DataFrame em um CSV
merged_df.to_csv(r'C:\Users\claud\OneDrive\Área de Trabalho\Iniciação Científica\Chikunguya-CAPTO\assets\data\Atlas_Zoonoses.csv', index=False)

## Merge Atlas_Zoonoses e Sanemento Básico

In [4]:
import pandas as pd

# Criar DataFrames de exemplo
df1_2 = pd.read_csv(r'C:\Users\claud\OneDrive\Área de Trabalho\Iniciação Científica\Chikunguya-CAPTO\assets\data\Atlas_Zoonoses.csv', delimiter=',', encoding='latin1')
df2_2 = pd.read_csv(r'C:\Users\claud\OneDrive\Área de Trabalho\Iniciação Científica\Chikunguya-CAPTO\assets\data\ibge_cnv_sanmg.csv', delimiter=',', encoding='latin1')

In [5]:
# Igualando o tipo de dados dos dois ID
df1_2['ID'] = df1_2['ID'].astype('Int64')
df2_2['ID'] = df2_2['ID'].astype('Int64')

#Transformando codmun6 em ID2
df1_2.rename(columns={'Codmun6': 'ID2'}, inplace=True)

In [6]:
df1_2.head()

,ANO,UF,ID2,ID,MunicÂ­pio,ESPVIDA,FECTOT,MORT1,MORT5,RAZDEP,...,Leptospirose,Verminoses,CÃ³lera,Difteria,Tifo,MalÃ¡ria,Hepatite,Febre amarela,Dermatite,DoenÃ§a do aparelho respiratÃ³rio
0,1991,11,110001,1100015,ALTA FLORESTA D'OESTE,"62,01","4,08","45,58","58,05","73,5",...,-,1,-,-,-,-,-,-,-,-
1,2000,11,110001,1100015,ALTA FLORESTA D'OESTE,"66,9","3,11","28,36","33,96","61,65",...,-,1,-,-,-,-,-,-,-,-
2,2010,11,110001,1100015,ALTA FLORESTA D'OESTE,"70,75","2,24","23,8","25,49","47,37",...,-,1,-,-,-,-,-,-,-,-
3,1991,11,110002,1100023,ARIQUEMES,"66,02","3,72","32,39","41,41","69,97",...,-,-,-,-,-,-,-,-,-,-
4,2000,11,110002,1100023,ARIQUEMES,"69,52","2,77","21,68","25,99","59,88",...,-,-,-,-,-,-,-,-,-,-

In [7]:
df2_2.head()

,Rede geral de esgoto ou pluvial nao discriminado,Fossa Séptica nao discriminado,Fossa rudimentar nao discriminado,Vala nao discriminado,Rio ou lago ou mar,Outro escoadouro nao discriminado,Nao tem instalacoes sanitarias,Total,ID,Municipio
0,1320,94,770,15,68,28,19,2314,310010,ABADIA DOS DOURADOS
1,6087,436,1093,8,17,7,56,7704,310020,ABAETE
2,1928,51,168,95,1513,158,17,3930,310030,ABRE CAMPO
3,767,34,113,3,340,1,3,1261,310040,ACAIACA
4,1189,180,251,75,1097,136,119,3047,310050,ACUCENA

In [8]:
import pandas as pd

# Mesclar com base em ID1 e ID2
merged_df_2 = df1_2.merge(df2_2, left_on='ID2', right_on='ID', how='outer')

# Mostrar DataFrame mesclado
print(merged_df_2)

        ANO  UF     ID2     ID_x             MunicÂ­pio ESPVIDA FECTOT  MORT1  \
0      1991  11  110001  1100015  ALTA FLORESTA D'OESTE   62,01   4,08  45,58
1      2000  11  110001  1100015  ALTA FLORESTA D'OESTE    66,9   3,11  28,36
2      2010  11  110001  1100015  ALTA FLORESTA D'OESTE   70,75   2,24   23,8
3      1991  11  110002  1100023              ARIQUEMES   66,02   3,72  32,39
4      2000  11  110002  1100023              ARIQUEMES   69,52   2,77  21,68
...     ...  ..     ...      ...                    ...     ...    ...    ...
16687  2000  52  522230  5222302         VILA PROPÂCIO   68,99   3,41   29,3
16688  2010  52  522230  5222302         VILA PROPÂCIO   73,09   2,67   15,9
16689  1991  53  530010  5300108              BRASÂLIA   68,87   2,33  27,35
16690  2000  53  530010  5300108              BRASÂLIA   73,86   1,96  20,71
16691  2010  53  530010  5300108              BRASÂLIA   77,35   1,75  14,01

       MORT5 RAZDEP  ... Rede geral de esgoto ou pluvial nao discriminado  \
0      58,05   73,5  ...                                              NaN
1      33,96  61,65  ...                                              NaN
2      25,49  47,37  ...                                              NaN
3      41,41  69,97  ...                                              NaN
4      25,99  59,88  ...                                              NaN
...      ...    ...  ...                                              ...
16687   34,5  62,64  ...                                              NaN
16688   18,8  50,75  ...                                              NaN
16689  31,75  57,01  ...                                              NaN
16690  24,04  46,49  ...                                              NaN
16691  15,85  40,14  ...                                              NaN

      Fossa Séptica nao discriminado Fossa rudimentar nao discriminado  \
0                                NaN                               NaN
1                                NaN                               NaN
2                                NaN                               NaN
3                                NaN                               NaN
4                                NaN                               NaN
...                              ...                               ...
16687                            NaN                               NaN
16688                            NaN                               NaN
16689                            NaN                               NaN
16690                            NaN                               NaN
16691                            NaN                               NaN

      Vala nao discriminado Rio ou lago ou mar  \
0                       NaN                NaN
1                       NaN                NaN
2                       NaN                NaN
3                       NaN                NaN
4                       NaN                NaN
...                     ...                ...
16687                   NaN                NaN
16688                   NaN                NaN
16689                   NaN                NaN
16690                   NaN                NaN
16691                   NaN                NaN

      Outro escoadouro nao discriminado Nao tem instalacoes sanitarias  \
0                                   NaN                            NaN
1                                   NaN                            NaN
2                                   NaN                            NaN
3                                   NaN                            NaN
4                                   NaN                            NaN
...                                 ...                            ...
16687                               NaN                            NaN
16688                               NaN                            NaN
16689                               NaN                            NaN
16690                               NaN                            NaN
16691                               NaN                            NaN

      Total_y  ID_y Municipio
0         NaN  <NA>       NaN
1         NaN  <NA>       NaN
2         NaN  <NA>       NaN
3         NaN  <NA>       NaN
4         NaN  <NA>       NaN
...       ...   ...       ...
16687     NaN  <NA>       NaN
16688     NaN  <NA>       NaN
16689     NaN  <NA>       NaN
16690     NaN  <NA>       NaN
16691     NaN  <NA>       NaN

[16692 rows x 263 columns]

In [18]:
# Configurar para exibir todas as colunas
pd.set_option('display.max_columns', None)

merged_df_2.head()

,ANO,UF,ID2,ID_x,MunicÂ­pio,ESPVIDA,FECTOT,MORT1,MORT5,RAZDEP,SOBRE40,SOBRE60,T_ENV,E_ANOSESTUDO,T_ANALF11A14,T_ANALF15A17,T_ANALF15M,T_ANALF18A24,T_ANALF18M,T_ANALF25A29,T_ANALF25M,T_ATRASO_0_BASICO,T_ATRASO_0_FUND,T_ATRASO_0_MED,T_ATRASO_1_BASICO,T_ATRASO_1_FUND,T_ATRASO_1_MED,T_ATRASO_2_BASICO,T_ATRASO_2_FUND,T_ATRASO_2_MED,T_FBBAS,T_FBFUND,T_FBMED,T_FBPRE,T_FBSUPER,T_FLBAS,T_FLFUND,T_FLMED,T_FLPRE,T_FLSUPER,T_FREQ0A3,T_FREQ11A14,T_FREQ15A17,T_FREQ18A24,T_FREQ25A29,T_FREQ4A5,T_FREQ4A6,T_FREQ5A6,T_FREQ6,T_FREQ6A14,T_FREQ6A17,T_FREQFUND1517,T_FREQFUND1824,T_FREQFUND45,T_FREQMED1824,T_FREQMED614,T_FREQSUPER1517,T_FUND11A13,T_FUND12A14,T_FUND15A17,T_FUND16A18,T_FUND18A24,T_FUND18M,T_FUND25M,T_MED18A20,T_MED18A24,T_MED18M,T_MED19A21,T_MED25M,T_SUPER25M,CORTE1,CORTE2,CORTE3,CORTE4,CORTE9,GINI,PIND,PINDCRI,PMPOB,PMPOBCRI,PPOB,PPOBCRI,PREN10RICOS,PREN20,PREN20RICOS,PREN40,PREN60,PREN80,PRENTRAB,R1040,R2040,RDPC,RDPC1,RDPC10,RDPC2,RDPC3,RDPC4,RDPC5,RDPCT,RIND,RMPOB,RPOB,THEIL,CPR,EMP,P_AGRO,P_COM,P_CONSTR,P_EXTR,P_FORMAL,P_FUND,P_MED,P_SERV,P_SIUP,P_SUPER,P_TRANSF,REN0,REN1,REN2,REN3,REN5,RENOCUP,T_ATIV,T_ATIV1014,T_ATIV1517,T_ATIV1824,T_ATIV18M,T_ATIV2529,T_DES,T_DES1014,T_DES1517,T_DES1824,T_DES18M,T_DES2529,THEILtrab,TRABCC,TRABPUB,TRABSC,T_AGUA,T_BANAGUA,T_DENS,T_LIXO,T_LUZ,AGUA_ESGOTO,PAREDE,T_CRIFUNDIN_TODOS,T_FORA4A5,T_FORA6A14,T_FUNDIN_TODOS,T_FUNDIN_TODOS_MMEIO,T_FUNDIN18MINF,T_M10A14CF,T_M15A17CF,T_MULCHEFEFIF014,T_NESTUDA_NTRAB_MMEIO,T_OCUPDESLOC_1,T_RMAXIDOSO,T_SLUZ,HOMEM0A4,HOMEM10A14,HOMEM15A19,HOMEM20A24,HOMEM25A29,HOMEM30A34,HOMEM35A39,HOMEM40A44,HOMEM45A49,HOMEM50A54,HOMEM55A59,HOMEM5A9,HOMEM60A64,HOMEM65A69,HOMEM70A74,HOMEM75A79,HOMEMTOT,HOMENS80,MULH0A4,MULH10A14,MULH15A19,MULH20A24,MULH25A29,MULH30A34,MULH35A39,MULH40A44,MULH45A49,MULH50A54,MULH55A59,MULH5A9,MULH60A64,MULH65A69,MULH70A74,MULH75A79,MULHER80,MULHERTOT,PEA,PEA1014,PEA1517,PEA18M,peso1,PESO1114,PESO1113,PESO1214,peso13,PESO15,peso1517,PESO1524,PESO1618,PESO18,Peso1820,PESO1824,Peso1921,PESO25,peso4,peso5,peso6,PESO610,Peso617,PESO65,PESOM1014,PESOM1517,PESOM15M,PESOM25M,pesoRUR,pesotot,pesourb,PIA,PIA1014,PIA1517,PIA18M,POP,POPT,I_ESCOLARIDADE,I_FREQ_PROP,IDHM,IDHM_E,IDHM_L,IDHM_R,#,MunicÃ­pio,Total_x,Dengue,Total geral de municÃ­pios,DiarrÃ©ia,Leptospirose,Verminoses,CÃ³lera,Difteria,Tifo,MalÃ¡ria,Hepatite,Febre amarela,Dermatite,DoenÃ§a do aparelho respiratÃ³rio,Rede geral de esgoto ou pluvial nao discriminado,Fossa Séptica nao discriminado,Fossa rudimentar nao discriminado,Vala nao discriminado,Rio ou lago ou mar,Outro escoadouro nao discriminado,Nao tem instalacoes sanitarias,Total_y,ID_y,Municipio
0,1991,11,110001,1100015,ALTA FLORESTA D'OESTE,"62,01","4,08","45,58","58,05","73,5","83,81","66,87","1,82","6,68","9,74","8,35","23,55","10,82","25,71","15,59","31,39","30,32","33,34","53,26","24,96","27,33","16,63","44,72","39,33","30,11","62,66","76,98","10,28","8,69","0,28","57,69","65,24","3,6","8,69","0,28",NaN,"66,19","31,22","8,93","6,1",NaN,NaN,"17,29",25,"65,42","58,08","26,48","4,16",NaN,"2,01",0,0,"17,32","22,77","5,84","7,09","12,74","11,65","11,21","3,21","4,31","4,74","3,91","4,91","0,65","39,18","70,52","117,53","235,05","352,58","0,63","39,21","47,11","65,55","71,89","83,15","87,03","52,46","2,26","66,65","7,56","16,9","33,35","96,53","27,75","17,63","198,46","22,46","1041,07","52,57","92,69","163,18","661,37","203,52","36,83","61,89","88,9","0,73",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"21,92","18,47","52,8","6,82","36,8","7,45",NaN,NaN,NaN,"34,58","37,1","33,34",NaN,0,"14,41","6,14",NaN,NaN,"1,57","63,2",1684,1584,1413,1212,1109,923,711,521,464,395,327,1580,232,132,54,38,12401,25,1634,1479,1414,1089,980,766,578,440,364,288,219,1587,132,75,47,33,25,11146,NaN,NaN,NaN,NaN,700,2387,1816,1771,1986,14000,1742,5128,1709,12258,1571,3386,1467,8872,633,604,634,3238,7367,428,1479,730,6447,3944,14167,23546,9379,NaN,NaN,NaN,NaN,23417,22835,"0,117","0,109","0,329","0,112","0,617","0,516",1,Alta Floresta D'Oeste (RO),1,1,1,1,-,1,-,-,-,-,-,-,-,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN
1,2000,11,110001,1100015,ALTA FLORESTA D'OESTE,"66,9","3,11","28,36","33,96","61,65","89,61","75,4","3,35","7,76","2,32","2,6","15,84","4,11","17,42","6,37","21,54","49,82","54,43","62,62","25,57","26,1","34,18","24,62","19,47","3,21","85,5","99,9","40,47","9,63","5,19","76,88","85,59","18,01","9,63","2,22","0,65","81,14","51,4","16,15","7,22","16,14","27,51","40,74","58,64","86,78","78,21","30,52","3,46","5,58","7,7","0,35",0,"44,96","51,27","27,23","35,23","32,77","19,52","15,39","8,43","14,84","9,41","13,47","7,73","1,13","86,28","147,38","261,58","447,52","780,84","0,58","16,15","23,67","35,59","47,74","58,46","69,78","46,94","2,26","62,31","8,78","19,64","37,69","89,65","21,38","14,19","371,15","42,01","1742,35","120,95","201,5","334,88","1156,41","386,54","33,41","73,5","117,83","0,59","47,37","1,83","55,54","8,73","2,93","0,2","22,83","22,51","11,6","24,69","0,54","1,38","5,25","12,51","56,22","82,67","89,08","94,44",NaN,"47,76","25,22","64,45","67,66","69,3","73,06","6,57","9,77","10,96","8,77","5,85","7,9","0,6","15,35","2,46","20,48","57,13","42,56","37,84","70,33","70,14","27,52",0.0,"70,32","83,86","13,22","62,92","43,34","72,51",0,"12,58","10,93","19,73",0.0,"1,19","29,86",1496,1570,1522,1292,1144,1081,1026,852,597,428,366,1677,345,249,155,74,13924,50,1372,1532,1472,1216,1118,977,925,648,476,356,324,1580,251,170,101,45,46,12609,12670.0,767.0,1179.0,10724.0,515,2453,1899,1780,1747,17300,1848,5502,1793,15458,1699,3654,1588,11802,606,655,634,3251,7552,890,1532,895,8123,5437,14192,26533,12341,20346.0,3040.0,1830.0,15476.0,25920,24888,"0,195","0,303","0,483","0,262","0,698","0,617",1,Alta Floresta D'Oeste (RO),1,1,1,1,-,1,-,-,-,-,-,-,-,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN
2,2010,11,110001,1100015,ALTA FLORESTA D'OESTE,"70,75","2,24","23,8","25,49","47,37","94,5","83,18","5,84","8,67","1,22","1,52","11,99","1,68",13,"2,72","15,76","57,62","63,21","66,39","20,36","18,97","25,81","22,03","17,82","7,79","90,45","107,69","45,99","35,4","21,23","85,25","92,88","34,6","34,15","10,5","4,89","95,55","79,6","22,78","9,28","39,18","54,07","70,79","81,62","95,68","91,19","29,58","1,61","5,03","4,73","0,54","2,73","85,65","87,98","54,51","63,55","67,6","36,8","29,39","40,46","39,81","23,19","38,61","19,19","5,51","102,4","224,8","368,9","586,67",877,"0,58","14,29","19,01","26,04","37,33","47,12","62,99","44,81","1,55","59,87","8,27","20,43","40,13","79,37","21,68","14,45","476,99","36,89","2137,18","160,31","289,97","469,88","1424,61","512,46","14,29","56,64","120,71","0,6","34,73","2,83","38,56","13,78","5,31",0,"41,68","45,49","31,05","33,18","0,69","7,72","3,26","9,63","36,23","78,8","88,52","95,9","950,08","51,93","9,08","28,98","63,44","60,43","62,94","6,07","10,51","23,16","10,25","5,17","5,06","0,52","25,17","5,31","23,17","93,69","80,2","22,58","94,05","93,98","9,31","7,18","45,73","60,82","4,32","40,27","24,81","54,06",0,"6,75","14,51","16,12","1,15","2,2","6,02",956,1256,1362,1105,1053,951,878,913,846,631,489,1073,351,301,239,154,12656,98,952,1145,1226,1095,1039,916,917,802,720,515,431,1034,311,264,177,119,73,11736,10611.0,218.0,464.0,9928.0,369,1883,1397,1434,1140,17976,1577,4788,1536,16399,1497,3211,1433,13188,399,429,413,2196,5170,1425,1145,747,8605,6284,10422,24392,13970,20434.0,2401.0,1602.0,16431.0,24097,22429,"0,368","0,629","0,641","0,526","0,763","0,657",1,Alta Floresta D'Oeste (RO),1,1,1,1,-,1,-,-,-,-,-,-,-,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN
3,1991,11,110002,1100023,ARIQUEMES,"66,02","3,72","32,39","41,41","69,97","88,08","74,23","1,82","7,86","9,35","7,64","17,18",8,"18,37","10,55","22,32","37,37","40,76","45,41","25,11","26,42","44,13","37,52","32,82","10,45","69,79","82,18","25,02","17,94","2,09","62,78","69,19","11,63","17,94","0,71",NaN,"73,34","41,92","13,56","4,15",NaN,NaN,"28,59","37,29","70,03","63,94","26,95","6,13",NaN,"4,61","0,28","0,38","32,53","41,93","13,67","17,45","22,3","19,98","19,08","4,67","6,3","10,17","5,73","11,67","3,13","72,08","133,98","214,9","419,96","656,26","0,57","18,9","25,47","41,3","52,24","65,78","74,41","44,91","2,62","61,27","9,12","19,77","38,73","94,73","19,69","13,43","319,47","41,9","1434,68","103,82","170,1","302,89","978,66","325,53","40,2","74,85","116,7","0,59",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"53,3","48,5","54,1","78,3","73,28","2,55",NaN,NaN,NaN,"29,97","33,27","24,75",NaN,"1,03","13,25","13,86",NaN,NaN,"1,66","26,72",3964,3627,3134,2947,2823,2289,1862,1393,1070,836,672,3802,473,321,150,77,29495,59,3819,3480,3184,3003,2610,2039,1654,1189,857,624,468,3661,303,202,121,61,47,27318,NaN,NaN,NaN,NaN,1614,5636,4279,4131,4624,34461,3811,12268,3818,30650,3699,8458,3663,22193,1546,1535,1449,7399,16845,1035,3480,1726,16358,10171,11529,56812,45283,NaN,NaN,NaN,NaN,56061,55018,"0,2","0,199","0,432","0,199","0,684","0,593",2246,Ariquemes (RO),-,-,1,-,-,-,-,-,-,-,-,-,-,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN
4,2000,11,110002,1100023,ARIQUEMES,"69,52","2,77","21,68","25,99","59,88","91,91","80,15","2,92","7,61","2,64","2,52","11,77","3,57","12,81","5,28","15,76","52,48","58,38","54,89","21,16","21,67","24,89","26,35","19,96","20,22","65,7","76,08","34,92","20,81","6,57","55,27","61,64","13,88","18,93","2,03","2,6","91,92","63,14","21,23","11,43","23,04","36,48","47,73","61,94","89,44","82,81","21,79","4,15","2,41","6,62","0,24","0,73","40,53","50,02","38,76","42,36","43,9","31,36","27,46","16,28","19,42","16,3","20,15","15,33","3,4","130,14","227,74","325,35","610,52","1046,32","0,59","8,01","11,46","21,55","30,03","47,55","59,38","48,31","2,79","63,57","9,53","19,73","36,43","88,94","20,27","13,34","530,87","73,96","2564,65","179,08","270,76","443,24","1687,3","545,77","32,83","78,27","144,3","0,59","30,9","4,27","21,6","16,75","6,49","1,02","41,42","36,12","20,64","36,35","0,46","3,91","12,23","6,05","38,42","72,24","80,71","91,3",NaN,"45,39","12,53","51,41","70,13","68,82","72,74","9,82","12,55","23,18","13,04","8,53",10,"0,54","30,7","5,38","23,03","73,54","67,08","37,55","90,61","93,43","21,14",0.0,"51,17","76,96","10,56","46,03","29,61","55,81","1,56","11,16","20,33","15,6",0.0,"1,6","6,57",4498,4269,4072,3571,3247,3165,2771,2248,1659,1228,919,4353,751,551,367,184,37995,142,4177,4206,4117,3774,3479,3132,2517,1980,1512,1086,804,4221,569,426,246,146,116,36508,33705.0,1038.0,2668.0,29999.0,1784,6771,5112,5027,5075,48771,4922,15534,5040,43857,4812,10612,4550,33238,1816,1840,1720,8438,20131,2178,4206,2527,23904,16013,19385,74503,55118,57064.0,8285.0,5190.0,43589.0,71789,69829,"0,314","0,358","0,556","0,343","0,742","0,674",2246,Ariquemes (RO),-,-,1,-,-,-,-,-,-,-,-,-,-,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN

#### Salvando em CSV a fusão

In [9]:
# Salvar o DataFrame em um CSV
merged_df_2.to_csv(r'C:\Users\claud\OneDrive\Área de Trabalho\Iniciação Científica\Chikunguya-CAPTO\assets\data\dados_integrados_MG.csv', index=False)

### Checando se a fusão foi bem sucedida

In [14]:
# Encontrar o índice da linha com ID2 = 2
index = merged_df_2.loc[merged_df_2['ID2'] == 310010].index[0]

# Exibir as linhas próximas (neste caso, 2 linhas antes e 2 linhas depois)
print(merged_df_2.iloc[max(0, index - 2):index + 3])

       ANO  UF     ID2     ID_x           MunicÂ­pio ESPVIDA FECTOT  MORT1  \
6724  2000  29  293360  2933604          XIQUE-XIQUE   61,76   3,84  54,27
6725  2010  29  293360  2933604          XIQUE-XIQUE   69,48   2,85     29
6726  1991  31  310010  3100104  Abadia dos Dourados   68,67   2,56  27,69
6727  2000  31  310010  3100104  Abadia dos Dourados   72,92   2,54  20,51
6728  2010  31  310010  3100104  Abadia dos Dourados   75,35   1,97   14,8

      MORT5 RAZDEP  ... Rede geral de esgoto ou pluvial nao discriminado  \
6724  68,81  78,65  ...                                              NaN
6725  31,31  63,01  ...                                              NaN
6726  36,51  50,87  ...                                             1320
6727  22,47  46,04  ...                                             1320
6728  17,22  42,76  ...                                             1320

     Fossa Séptica nao discriminado Fossa rudimentar nao discriminado  \
6724                            NaN                               NaN
6725                            NaN                               NaN
6726                             94                               770
6727                             94                               770
6728                             94                               770

     Vala nao discriminado Rio ou lago ou mar  \
6724                   NaN                NaN
6725                   NaN                NaN
6726                    15                 68
6727                    15                 68
6728                    15                 68

     Outro escoadouro nao discriminado Nao tem instalacoes sanitarias Total_y  \
6724                               NaN                            NaN     NaN
6725                               NaN                            NaN     NaN
6726                                28                             19  2314.0
6727                                28                             19  2314.0
6728                                28                             19  2314.0

        ID_y            Municipio
6724    <NA>                  NaN
6725    <NA>                  NaN
6726  310010  ABADIA DOS DOURADOS
6727  310010  ABADIA DOS DOURADOS
6728  310010  ABADIA DOS DOURADOS

[5 rows x 263 columns]

### Convertendo  para excel na hora de salvar

In [15]:
merged_df_2.to_excel(r'C:\Users\claud\OneDrive\Área de Trabalho\Iniciação Científica\Chikunguya-CAPTO\assets\data\dados_integrados_MG.xlsx')

- Bem sucedido